/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

import Setores.SetoresDados;
import Usuario.FilaUsuarios;
import Usuario.Usuario;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class JSetorAtivo extends javax.swing.JFrame {

    /**
     * Creates new form JSetor
     */
    
    public Usuario usuario;
    public FilaUsuarios fila = new FilaUsuarios();
    public String nome_setor;
    public static int i = 1;
    SetoresDados dados_arquivo = new SetoresDados();
    
    DefaultTableModel modelo = new DefaultTableModel(){ 
    public boolean isCellEditable(int rowIndex, int mColIndex){ 
         return false; 
    }}; 
    
    public String sortear_chamada()
    {
        String chamada = usuario.getMatricula() + " - " + nome_setor;
        
        return chamada;
    }
    
    public JSetorAtivo(Usuario usuario, String nome_setor) {
        this.usuario = usuario;
        this.nome_setor = nome_setor;
        
        try {
            fila = dados_arquivo.ler_usuarios(nome_setor);
        } catch (IOException ex) {
            
        }
        
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(JSetorAtivo.DISPOSE_ON_CLOSE);
        
        modelo.addColumn("Matrícula");
        modelo.addColumn("CPF");
        
        jTableUsuarios.setModel(modelo);
        
        this.preencherTabela();
    }
    
    public void tirar_chamado_da_lista(Usuario chamado)
    {
        fila.remover(chamado.getMatricula());        
        this.preencherTabela();
    }
    
    public void preencherTabela()
    {
        modelo = (DefaultTableModel) jTableUsuarios.getModel();
        modelo.setRowCount(0);
        modelo.fireTableDataChanged();
        
        ArrayList<ArrayList<String>> users = fila.toArrayString();

        for(ArrayList<String> s: users)
        {
            modelo.addRow(new Object[]{s.get(0), s.get(1)});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnSairDaFila = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
        }

        btnCadastrar.setText("Cadastrar na Fila");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnSairDaFila.setText("Sair da Fila");
        btnSairDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairDaFilaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tempo Médio de Atendimento:");

        lblTempo.setText("00:00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSairDaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTempo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTempo))
                .addGap(8, 8, 8)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairDaFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String matricula = usuario.getMatricula();
        int linhas = jTableUsuarios.getRowCount();
        
        usuario.setChamada(this.sortear_chamada());
        
        boolean tem = this.tem_na_lista(linhas, matricula);
        if(tem)
        {
            JOptionPane.showMessageDialog(null, "Usuario já registrado!");
        }
        else
        {
            try {
                dados_arquivo.salvar(usuario, nome_setor);
            } catch (IOException ex) {
                Logger.getLogger(JSetorAtivo.class.getName()).log(Level.SEVERE, null, ex);
            }
            fila.enqueue(usuario.getMatricula(), usuario.getCpf());
        
            this.preencherTabela();
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed
    
    public void set_label_text(String tempo)
    {
        lblTempo.setText(tempo);
    }
    
    private void btnSairDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairDaFilaActionPerformed
        String matricula = usuario.getMatricula();
        int linhas = jTableUsuarios.getRowCount();
        boolean tem = this.tem_na_lista(linhas, matricula);
        
        if(tem)
        {
            fila.remover(matricula);        
            this.preencherTabela();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Usuario não registrado!");
        }
        
    }//GEN-LAST:event_btnSairDaFilaActionPerformed
    
    private Boolean tem_na_lista(int linhas, String matricula)
    {
        for(int i = 0; i < linhas; i++)
        {
            String item = (String) jTableUsuarios.getValueAt(i, 0);
            if(item.equals(matricula))
            {
                return true;
            }
        }
        
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSetorAtivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSetorAtivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSetorAtivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSetorAtivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSetorAtivo(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSairDaFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JLabel lblTempo;
    // End of variables declaration//GEN-END:variables
}
