/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

import Setores.ListaSetores;
import Setores.SetoresDados;
import Usuario.Usuario;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class JUsuarios extends javax.swing.JFrame {

    Usuario user;
    public JSetorAtivo jsetor;
    /**
     * Creates new form JUsuarios
     */
    ListaSetores setores = new ListaSetores();
    SetoresDados dados_arquivo = new SetoresDados();
    Boolean vazio = false;
    
    DefaultTableModel modelo_chamada = new DefaultTableModel();
    
    DefaultTableModel modelo = new DefaultTableModel(){ 
    public boolean isCellEditable(int rowIndex, int mColIndex){ 
         return false; 
    }}; 

    public JUsuarios() {
        initComponents();
        setDefaultCloseOperation(JUsuarios.DISPOSE_ON_CLOSE);
        
        JLoginUsuario jlogin = new JLoginUsuario(this);
        jlogin.setVisible(true);
        
        try {
            setores = dados_arquivo.ler_setores();
        } catch (IOException ex) {
            vazio = true;
        }
        
        modelo.addColumn("Nome");
        
        if(!vazio)
        {
            this.preencherTabela();

        }
        
        jTableSetores.setModel(modelo);
        
        jTableSetores.addMouseListener( new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2) {
                    DefaultTableModel tableModel = (DefaultTableModel) jTableSetores.getModel();
                    int row = jTableSetores.getSelectedRow();
                    String nome_setor = tableModel.getValueAt(row, 0).toString();
                    jsetor = new JSetorAtivo(user, nome_setor);
                    jsetor.setVisible(true);
                }
            }
        });
        
        modelo_chamada.addColumn("Chamada");
        jTableUltimasChamadas.setModel(modelo_chamada);
        this.preencherChamadas();
    }
    
    public void receber_usuario(Usuario user)
    {
        this.user = user;
    }
    
    public void preencherChamadas()
    {
        ArrayList<String> chamadas = new ArrayList<>();
        
        modelo = (DefaultTableModel) jTableUltimasChamadas.getModel();
        modelo.setRowCount(0);
        modelo.fireTableDataChanged();
        
        try {
            chamadas = dados_arquivo.ler_chamada();
        } catch (IOException ex) {
            Logger.getLogger(JUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(String s : chamadas)
        {
            modelo_chamada.addRow(new Object[]{s});
        }
        
    }
    
    public void preencherTabela()
    {
        ArrayList<String> nomeSetores = setores.toArrayNome();
        
        modelo = (DefaultTableModel) jTableSetores.getModel();
        modelo.setRowCount(0);
        modelo.fireTableDataChanged();
        
        for(String s : nomeSetores)
        {
            modelo.addRow(new Object[]{s});
        }
    }
    
    public void receber_setores(ListaSetores dadosSetores)
    {
        try {
            setores = dados_arquivo.ler_setores();
        } catch (IOException ex) {
            Logger.getLogger(JUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.preencherTabela();
    }
    
    public void receber_chamadas()
    {
        this.preencherChamadas();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSetores = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUltimasChamadas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSair = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Selecione o setor e suas opções");

        jTableSetores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSetores.setCellSelectionEnabled(true);
        jTableSetores.setRowHeight(25);
        jScrollPane2.setViewportView(jTableSetores);
        jTableSetores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTableSetores.getColumnModel().getColumnCount() > 0) {
            jTableSetores.getColumnModel().getColumn(0).setResizable(false);
        }

        jTableUltimasChamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUltimasChamadas);
        if (jTableUltimasChamadas.getColumnModel().getColumnCount() > 0) {
            jTableUltimasChamadas.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Ultimos Chamados");

        jMenuSair.setText("Sair");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenuSair.add(mnSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSetores;
    private javax.swing.JTable jTableUltimasChamadas;
    private javax.swing.JMenuItem mnSair;
    // End of variables declaration//GEN-END:variables
}
